
#General Settings
[general]
	#How many slots for unique blocks the bit bag have
	#Range: 3 ~ 12
	typeSlotsPerBag = 12
	#The maximum of measurements of the tape measure you can have at once.
	#Range: > 1
	tapeMeasureLimit = 10
	#The maximum amount of possible undo operations that will be remembered at any time.
	#Range: > 1
	maxUndoLevel = 32
	#How many bits fit in each slot of the bit bag
	#Range: 1 ~ 9223372036854775807
	bitsPerTypeSlot = 131072
	#Shows how many bits you've got left of the current type in the durability bar of the storage item.
	showBitsAvailableAsDurability = true
	#At how many blocks the width/length of the drawn region selection should be capped
	#Range: 1.0 ~ 16.0
	maxDrawnRegionSize = 4.0
	#How many slots for unique fluids the bit beaker has
	#Range: 3 ~ 12
	typeSlotsPerBeaker = 4
	#How many slots you have for bookmarks in the palette
	#Range: 3 ~ 12
	bookmarksPerPalette = 12
	#How big should the durability of a chisel be, each bit modified takes one durability.
	#Range: > 1
	chiselDurability = 1048576

